# 
# install cosign cli from release page: https://github.com/sigstore/cosign/releases
# install kubectl cli, e.g. for linux curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
# get cluster credentials to connect to Kubernetes cluster
# get MTR credentials to sign remote image
#
# kubectl create namespace demoapp
# cosign login mtr.devops.telekom.de -u xxxx -p xxxxx
# cosign generate-key-pair k8s://demoapp/cosign
# cosign sign --key k8s://demoapp/cosign mtr.devops.telekom.de/mcsps/test1:master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demoapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - image: mtr.devops.telekom.de/mcsps/test1:master
        imagePullPolicy: Always
        name: demoapp
        ports:
        - containerPort: 8080
          name: 8080tcp
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          runAsNonRoot: true
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: demoapp-config
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - verify
        - --key
        - k8s://demoapp/cosign
        - mtr.devops.telekom.de/mcsps/test1:master
        command:
        - cosign
        image: mtr.devops.telekom.de/mcsps/cosign:v1.8.0
        imagePullPolicy: Always
        name: sigcheck
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      nodeSelector:
        role: worker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: demoapp
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: demoapp-config
        name: demoapp-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demoapp-config
data:
  index.html: |
    <html>
    <body>
    <h1>Greetings from MCSPS</h1>
    </body>
    </html>
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: demoapp
  name: demoapp
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: demoapp
  name: demoapp
rules:
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: demoapp
  name: demoapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demoapp
subjects:
  - kind: ServiceAccount
    name: demoapp
