apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: helloworld

resources:
- helloworld/configmap.yaml
- helloworld/deployment.yaml
- helloworld/services.yaml
- helloworld/ingress.yaml

patchesJson6902:
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: helloworld-ingress
  path: helloworld/overlays/k8s00-test.yaml
