---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql-client
  name: mysql-client
spec:
  serviceName: mysql-client
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql-client
  template:
    metadata:
      labels:
        app: mysql-client
    spec:
      containers:
      - image: mtr.devops.telekom.de/mcsps/mcsps-tools:latest
        imagePullPolicy: Always
        command: ['sh', '-c']
        args: ["tail -f /dev/null"]
        name: mysql-client
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: true
          privileged: false
          readOnlyRootFilesystem: false
          runAsUser: 0
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: mysql-client
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: mysql-client
  name: mysql-client
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: mysql-client
  name: mysql-client
rules:
- apiGroups:
  - extensions
  resourceNames:
  - unrestricted-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: mysql-client
  name: mysql-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mysql-client
subjects:
  - kind: ServiceAccount
    name: mysql-client
