apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ingress
spec:
  rules:
  - host: demoapp.mcsps.telekomcloud.com
    http:
      paths:
      - backend:
          service:
            name: helloworld-service
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - demoapp.mcsps.telekomcloud.com
    secretName: demoapp-mcsps-telekomcloud-com
