---
apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [auth]
    disable_login_form = false
    [auth.anonymous]
    enabled = true
    org_role = Viewer
    [auth.basic]
    enabled = false
    [dashboards]
    default_home_dashboard_path = /tmp/dashboards/demoapp-default-home.json
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [users]
    auto_assign_org_role = Viewer
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: demoapp-monitoring
    app.kubernetes.io/name: grafana
  name: demoapp-monitoring-grafana
  namespace: demoapp
