---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: demoapp-monitoring
  name: demoapp-monitoring-flask
  namespace: demoapp
spec:
  groups:
  - name: demoapp-apps
    rules:
    - alert: Error404
      annotations:
        message: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) has Error 404.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping
      expr: flask_http_request_total{status="404"} > 0
      for: 1m
      labels:
        severity: critical
        app: demoapp
