---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: demoapp-monitoring
    app.kubernetes.io/name: grafana
  name: demoapp-monitoring-grafana
  namespace: demoapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demoapp-monitoring-grafana
subjects:
- kind: ServiceAccount
  name: demoapp-monitoring-grafana
  namespace: demoapp
