---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: demoapp-monitoring-alertmanager
  name: demoapp-monitoring-alertmanager
  namespace: demoapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demoapp-monitoring-alertmanager
subjects:
- kind: ServiceAccount
  name: demoapp-monitoring-alertmanager
  namespace: demoapp
