---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demoapp-monitoring-prometheus
  namespace: demoapp
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
