---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: demoapp-monitoring-alertmanager
  name: demoapp-monitoring-alertmanager
  namespace: demoapp
rules:
- apiGroups:
  - policy
  resourceNames:
  - rancher-monitoring-alertmanager
  resources:
  - podsecuritypolicies
  verbs:
  - use
