---
apiVersion: v1
data:
  admin-password: cHJvbS1vcGVyYXRvcg==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: demoapp-monitoring
    app.kubernetes.io/name: grafana
  name: demoapp-monitoring-grafana
  namespace: demoapp
type: Opaque
