---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demoapp-monitoring-prometheus
    self-monitor: "true"
  name: demoapp-monitoring-prometheus
  namespace: demoapp
spec:
  ports:
  - name: nginx-http
    port: 9090
    protocol: TCP
    targetPort: 8080
  selector:
    app: prometheus
    prometheus: demoapp-monitoring-prometheus
  sessionAffinity: None
  type: ClusterIP
