---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: demoapp
  name: demoapp-monitoring-demoapp
  namespace: demoapp
spec:
  endpoints:
    - port: http
      interval: 5s
      path: /metrics
  selector:
    matchLabels:
      app: demoapp
