---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demoapp-monitoring-alertmanager
    self-monitor: "true"
  name: demoapp-monitoring-alertmanager
  namespace: demoapp
spec:
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    alertmanager: demoapp-monitoring-alertmanager
    app: alertmanager
  sessionAffinity: None
  type: ClusterIP
