apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-ssd-test-restore
spec:
  storageClassName: ssd
  dataSource:
    name: csi-ssd-test-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
