apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: curl
  name: curl
spec:
  backoffLimit: 1
  completions: 10
  parallelism: 10
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: mtr.devops.telekom.de/rancher/mirrored-curlimages-curl:7.77.0
        imagePullPolicy: IfNotPresent
        name: curl
        command: ["sh"]
        args: ["-c","curl -v demoapp.demoapp/a && exit 0"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          runAsNonRoot: true
          runAsUser: 1000
        resources:
          requests:
            cpu: 1m
            memory: 8Mi
          limits:
            cpu: 100m
            memory: 128Mi
