apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: curlplus
  name: curlplus
spec:
  backoffLimit: 0
  completions: 100
  parallelism: 100
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: mtr.external.otc.telekomcloud.com/rancher/mirrored-curlimages-curl:7.77.0
        imagePullPolicy: IfNotPresent
        name: curl
        command: ["sh"]
        args: ["-c","while x=0;do curl -v demoapp.demoapp/a; done && exit 0"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          runAsNonRoot: true
          runAsUser: 1000
        resources:
          requests:
            cpu: 1m
            memory: 8Mi
          limits:
            cpu: 100m
            memory: 128Mi
